CREATE TABLE users (
	id BIGINT PRIMARY KEY,
	display_name VARCHAR(120) NOT NULL,
	email VARCHAR(120) UNIQUE NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOW NULL DEFAULT now(),
	deleted_at TIMESTAMPTZ,
	is_active BOOLEAN NOT NULL DEFAULT true
);