CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    
    title VARCHAR(255) NOT NULL,
    volume VARCHAR(100) NOT NULL,
    publisher VARCHAR(100) NOT NULL,
    author VARCHAR(100) NOT NULL,
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    FOREIGN KEY (user_id) REFERENCES users(id),
    UNIQUE (user_id, book_id)
);